#!/usr/bin/python3

import MySQLdb
import sys

def list_citis_by_states(username, password, database, state_name):
    """
    takes in the name of a state as an argument and lists all cities
    of that state, using the database hbtn_0e_4_usa.
    Args:
        username = mysql username
        password = mysql password
        database = mysql database
        state_name = state searched
    """
    db = MySQLdb.connect(
            user=username,
            passwd=password,
            db=database,
            host='localhost',
            port=3306
            )
    mycursor = db.cursor()
    sql_query = ("SELECT 
                cities.id, cities.name, states.name
